apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
    - port: 8080
  selector:
    app: backend-data

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  name: backend-ingress
spec:
  rules:
  - http:
      paths:
        - path: /todo
          backend:
            serviceName: backend
            servicePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-data
    spec:
      containers:
      - name: backend
        image: "doclusterdemo/backend:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          privileged: false
        env:
          - name: CASSANDRA_CONTACT_POINT
            value: "cassandra-0.cassandra.default.svc.cluster.local"
        readinessProbe:
          httpGet:
            path: /admin/healthcheck
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
