apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 9090
      targetPort: web
  selector:
    app: frontend-data

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  name: frontend-ingress
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: frontend
            servicePort: 9090

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-data
    spec:
      containers:
      - name: backend
        image: "doclusterdemo/frontend:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: false
        env:
          - name: API_ROOT_URL
            value: "http://--api-url-public-replace--/todo"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 5
